[tool.poetry]
name = "quickbrief"
version = "0.1.0"
description = ""
authors = ["y-tsuritani"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
diagrams = "^0.23.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
